"""Deterministic schedule coach: produce repair suggestions from scheduler output.

All suggestions are generated by application code from the validated draft and
real scheduler result.  LLM output must never invent executable repair operations.
"""

from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.ai.context import ChatContext
    from app.schemas.drafts import TaskDraft, TodayDraft

# Threshold below which a task's duration qualifies for reduce-duration suggestions
_REDUCE_THRESHOLD_MIN = 60
# Minimum allowed duration (spec: 5 minutes)
_MIN_DURATION_MIN = 5
# Long-task split threshold (spec: tasks longer than this may be suggested for split)
_SPLIT_THRESHOLD_MIN = 90


def _optional_tasks(draft: "TodayDraft") -> list["TaskDraft"]:
    return [t for t in draft.tasks if t.importance == "OPTIONAL"]


def suggest_remove_optional(draft: "TodayDraft", unscheduled_ids: list[str] = None) -> list[dict]:
    """PV-007: Suggest removing an OPTIONAL task.

    Returns at most one suggestion per OPTIONAL task, targeting the lowest-priority
    one first.  Never targets CORE tasks.  Produces a canonical remove-task patch.
    Rendering causes no mutation; mutation only after explicit click.
    """
    candidates = _optional_tasks(draft)
    if unscheduled_ids:
        candidates = [c for c in candidates if c.id in unscheduled_ids] or candidates
    candidates = sorted(
        candidates,
        key=lambda t: (
            {"HIGH": 0, "MEDIUM": 1, "LOW": 2}.get(t.priority, 1),
            t.durationMin,
        ),
        reverse=True,  # Highest duration / lowest priority first
    )
    suggestions = []
    for task in candidates[:1]:  # One suggestion at a time
        suggestions.append(
            {
                "label": f"Remove optional: {task.title}",
                "patch": [{"op": "remove_task", "task_id": task.id}],
            }
        )
    return suggestions


def suggest_move_to_tomorrow(
    draft: "TodayDraft", ctx: "ChatContext", unscheduled_ids: list[str] = None
) -> list[dict]:
    """PV-008: Suggest moving an eligible low-priority or OPTIONAL task to tomorrow.

    Uses server-owned timezone/date.  Does not move fixed tasks that would violate
    their constraint.  Does not mutate before explicit click.
    """
    tomorrow = (ctx.now.date() + timedelta(days=1)).isoformat()
    candidates = [
        t
        for t in draft.tasks
        if t.importance == "OPTIONAL" and t.schedulingType != "FIXED"
    ]
    if unscheduled_ids:
        candidates = [c for c in candidates if c.id in unscheduled_ids] or candidates
    candidates.sort(key=lambda t: ({"HIGH": 0, "MEDIUM": 1, "LOW": 2}.get(t.priority, 1), t.durationMin), reverse=True)
    suggestions = []
    for task in candidates[:1]:
        suggestions.append(
            {
                "label": f"Move to tomorrow: {task.title}",
                "patch": [
                    {
                        "op": "move_task_to_date",
                        "task_id": task.id,
                        "target_date": tomorrow,
                        "timezone": str(ctx.timezone),
                    }
                ],
            }
        )
    return suggestions


def suggest_extend_availability(
    draft: "TodayDraft", ctx: "ChatContext", extra_minutes: int = 30
) -> list[dict]:
    """PV-009: Suggest extending today's availability window.

    Only suggests if the extended end would not exceed the configured day-end boundary
    (22:00 by default).  Respects timezone.  Generates a canonical window patch.
    Does not create reversed or invalid windows.
    """
    from datetime import time

    day_end = time(22, 0)
    if not draft.windows:
        return []
    last_window = draft.windows[-1]
    try:
        from datetime import datetime

        current_end = datetime.strptime(last_window.end, "%H:%M").time()
    except ValueError:
        return []
    if current_end >= day_end:
        return []
    # New end capped at day_end
    from datetime import datetime as _dt

    new_end_dt = _dt.combine(_dt.today(), current_end) + timedelta(minutes=extra_minutes)
    new_end = min(new_end_dt.time(), day_end)
    new_end_str = new_end.strftime("%H:%M")
    if new_end_str <= last_window.end:
        return []
    return [
        {
            "label": f"Extend availability to {new_end_str} (+{extra_minutes} min)",
            "patch": [
                {
                    "op": "update_window",
                    "window_index": len(draft.windows) - 1,
                    "end": new_end_str,
                }
            ],
        }
    ]


def suggest_reduce_duration(draft: "TodayDraft", unscheduled_ids: list[str] = None) -> list[dict]:
    """PV-010: Suggest reducing duration for RULE or AI estimated tasks.

    Respects minimum duration (5 min).  Does not reduce USER estimates.
    Prefers eligible RULE or AI sources.  Preserves stable task IDs.
    """
    candidates = [
        t
        for t in draft.tasks
        if t.estimateSource in {"RULE", "AI"}
        and t.durationMin > _REDUCE_THRESHOLD_MIN
        and t.importance == "OPTIONAL"
    ]
    if unscheduled_ids:
        candidates = [c for c in candidates if c.id in unscheduled_ids] or candidates
    candidates.sort(key=lambda t: t.durationMin, reverse=True)
    suggestions = []
    for task in candidates[:1]:
        reduced = max(_MIN_DURATION_MIN, task.durationMin // 2)
        suggestions.append(
            {
                "label": f"Reduce {task.title} from {task.durationMin} to {reduced} min",
                "patch": [
                    {
                        "op": "update_task",
                        "task_id": task.id,
                        "duration_min": reduced,
                    }
                ],
            }
        )
    return suggestions


def suggest_split_long_task(draft: "TodayDraft") -> list[dict]:
    """PV-011: Suggest splitting a long task.

    Preserves total duration, importance, and estimate source.
    Does not split fixed intervals.  Result must pass validation.
    """
    candidates = [
        t
        for t in draft.tasks
        if t.durationMin > _SPLIT_THRESHOLD_MIN
        and t.schedulingType != "FIXED"
        and not t.splittable  # Suggest making splittable
    ]
    candidates.sort(key=lambda t: t.durationMin, reverse=True)
    suggestions = []
    for task in candidates[:1]:
        half = task.durationMin // 2
        remainder = task.durationMin - half
        suggestions.append(
            {
                "label": f"Split '{task.title}' into {half} + {remainder} min sessions",
                "patch": [
                    {
                        "op": "update_task",
                        "task_id": task.id,
                        "splittable": True,
                    }
                ],
            }
        )
    return suggestions


def generate_overloaded_suggestions(
    draft: "TodayDraft", ctx: "ChatContext", unscheduled_ids: list[str] = None
) -> list[dict]:
    """Generate deterministic coach suggestions when the scheduler returns OVERLOADED.

    Order: remove-optional, move-to-tomorrow, extend-availability, reduce-duration, split.
    All generated from application code — never from LLM output.
    """
    suggestions: list[dict] = []
    suggestions.extend(suggest_remove_optional(draft, unscheduled_ids))
    suggestions.extend(suggest_move_to_tomorrow(draft, ctx, unscheduled_ids))
    suggestions.extend(suggest_extend_availability(draft, ctx))
    suggestions.extend(suggest_reduce_duration(draft, unscheduled_ids))
    suggestions.extend(suggest_split_long_task(draft))
    return suggestions
