"""Add AiUsageLog

Revision ID: 8e47a157a9b0
Revises: b21e8a59c4d2
Create Date: 2026-09-20 16:46:05.454346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '8e47a157a9b0'
down_revision: Union[str, Sequence[str], None] = 'b21e8a59c4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ai_usage_recent_idx', 'ai_usage_log', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ai_usage_user_recent_idx', 'ai_usage_log', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ai_usage_user_recent_idx', table_name='ai_usage_log')
    op.drop_index('ai_usage_recent_idx', table_name='ai_usage_log')
    op.drop_table('ai_usage_log')
    # ### end Alembic commands ###
